language: node_js
sudo: false
node_js:
  - node
before_script:
  - gem install sass
  - gem install scss-lint
  - npm install
  - npm install -g gulp
  - gulp build
  - npm run cover
after_success:
  - npm run report-coverage